config/routes.rb
Rails.application.routes.draw do

#admin
devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
namespace :admins do

  resources :users,only: [:show,:edit,:update]
      get 'top'=>'users#top'
  resources :genres,only: [:index,:create,:edit,:update]
  resources :locations,only: [:index,:create,:edit,:update]

  root to: 'users#top'

end


#customers
devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
scope module: :customers do

  resources :users,only: [:index, :show, :new, :edit, :update] do
    resource :relationships, only: [:create, :destroy, :index]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      get 'quit'=>'users#quit'
      get 'out'=>'users#out'
  end
  resources :favorites,only: [:index]
  resources :genres,only: [:index]
  resources :locations,only: [:index]
  resources :relationships,only: [:index]
  resources :posts do
    resource :favorites,only: [:create, :destroy]
    resource :likes,only: [:create, :destroy]
  end

  get '/search' => 'search#search'

   root to: 'likes#about'
     get	'top' => 'likes#top'

  post "posts/:id/destroy" => "posts#destroy"

  devise_scope :user do
    get '/customers/sign_out' => 'devise/sessions#destroy'
  end
end

end

app/models/customer.rb
class Customer < ApplicationRecord


  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 enum gender: { 男性: 1, 女性: 2, その他: 3}

 # 退会機能
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

has_many :relationships,class_name: "Relationship",  foreign_key: "follower_id",dependent: :destroy
has_many :passive_relationships,class_name: "Relationship", foreign_key: "followed_id",dependent: :destroy
has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人
has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
has_many :followings, through: :relationships, source: :followed

def follow(customer_id)
    unless self == customer_id
     self.relationships.find_or_create_by(followed_id: customer_id.to_i, follower_id: self.id)
    end
end

def unfollow(customer_id)
    relationships.find_by(followed_id: customer_id).destroy
end

def following?(customer)
    followings.include?(customer)
end

end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!

  def top
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
    @posts = @customer.posts.page(params[:page]).per(10)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
  if @customer.update(customer_params)
   flash[:success] = "内容を変更しました!"
   redirect_to admins_user_path(@customer)
  else
   render :edit
  end
  end

  private

  def customer_params
   params.require(:customer).permit(:email, :name, :encrypted_password, :image, :is_deleted, :nickname, :gender)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/favorites_controller.rb
class Customers::FavoritesController < ApplicationController
 before_action :authenticate_customer!

  def create
    post = Post.find(params[:post_id])
    favorite = current_customer.favorites.new(post_id: post.id)
    favorite.save
    redirect_to posts_path
  end

  def destroy
    post = Post.find(params[:post_id])
    favorite = current_customer.favorites.find_by(post_id: post.id)
    favorite.destroy
    redirect_to posts_path
  end

  def index
    @posts = Post.page(params[:page]).per(10)
    @customer = Customer.find(params[:customer_id])
  end

end

app/controllers/customers/genres_controller.rb
class Customers::GenresController < ApplicationController
  before_action :authenticate_customer!

  def index
    @posts = Post.page(params[:page]).per(10)
  end
end

app/controllers/customers/homes_controller.rb
class Customers::HomesController < ApplicationController
end

app/controllers/customers/likes_controller.rb
class Customers::LikesController < ApplicationController
  before_action :authenticate_customer!

  def top
     @posts = Post.ranking.take(5)  #takeで上位５個を表示という意味、またはtakeじゃなくてlimitでも可能
     @genres = Genre.all
     @post = Post.order(created_at: :desc).limit(10)
  end

  def about
  end

  def create
    post = Post.find(params[:post_id])
    like = current_customer.likes.new(post_id: post.id)
    like.save
    redirect_to post_path(post)
  end

  def destroy
    post = Post.find(params[:post_id])
    like = current_customer.likes.find_by(post_id: post.id)
    like.destroy
    redirect_to post_path(post)
  end

end

app/controllers/customers/locations_controller.rb
class Customers::LocationsController < ApplicationController
   before_action :authenticate_customer!

   def index
   end

end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/posts_controller.rb
class Customers::PostsController < ApplicationController
 before_action :authenticate_customer!

 def index
  @posts = Post.page(params[:page]).per(6)
 end

 def new
  @post = Post.new
  @customer = Customer.new
 end

 def create
  @post = Post.new(post_params)
  @post.customer_id = current_customer.id
  if @post.save
   flash[:success] = "投稿しました!"
   redirect_to post_path(@post.id)
  else
   render :new
  end
 end

 def show
  @post = Post.find(params[:id])
  @customer = @post.customer
 end

 def edit
  @post = Post.find(params[:id])
 end

 def update
   @post = Post.find(params[:id])
  if @post.update(post_params)
   flash[:success] = "投稿内容を変更しました!"
   redirect_to post_path(@post)
  else
   render :edit
  end
 end

 def destroy
  @post = Post.find_by(id: params[:id])
  @post.destroy
  redirect_to posts_path
 end

 private

  def post_params
   params.require(:post).permit(:image, :name, :customer_id, :genre_id, :location_id, :statement, :evaluation, :address)
  end

 end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/relationships_controller.rb
class Customers::RelationshipsController < ApplicationController
  before_action :authenticate_customer!

  def create
    current_customer.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_customer.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    customer = Customer.find(params[:user_id])
    @customers = customer.followings
  end

  def followers
    customer = Customer.find(params[:user_id])
    @customers = customer.followers
  end

end

app/controllers/customers/search_controller.rb
class Customers::SearchController < ApplicationController
  before_action :authenticate_customer!

  def search
    @value = params["search"]["value"]         #データを代入
    @how = params["search"]["how"]             #データを代入
    @datas = search_for(@how, @value)          #def search_forを実行(引数に検索ワードと検索方法)
  end

  private

  def location(value)
    #.orを使用することで、valueに一致するカラムのデータをnameカラムとgenre_idカラムから探してきます。
    target_location_id = Location.find_by(name: value)&.id
    Post.where(location_id: target_location_id)
  end

  def customer(value)
    target_customer_id = Customer.find_by(nickname: value)&.id
    Post.where(customer_id: target_customer_id)
  end

  def genre(value)
    target_genre_id = Genre.find_by(name: value)&.id
    Post.where(genre_id: target_genre_id)
  end

  def post(value)
    Post.where("name LIKE ?", "#{value}%")
  end


  def search_for(how, value)
    case how                     #引数のhowと一致する処理に進むように定義しています。
    when 'location'                 #ジャンル検索の場合はmatchで固定してるので、必ず'match'の処理に進みます。
      location(value)
    when 'customer'
      customer(value)
    when 'genre'
      genre(value)
    when 'post'
      post(value)
    end
  end

end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def reject_inactive_customer
  @cusomer = Customer.find_by(name: params[:customer][:name])
    if @user
      if @customer.valid_password?(params[:cusomer][:password]) && !@cusomer.is_deleted
        redirect_to new_registration_path(resource_name)
      end
    end
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/users_controller.rb
class Customers::UsersController < ApplicationController
  before_action :authenticate_customer!

  def index
    @customers = Customer.page(params[:page]).per(10)
    @customer = current_customer
  end

  def show
    @customer = Customer.find(params[:id])
    @posts = @customer.posts.page(params[:page]).per(4)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
  if @customer.update(customer_params)
   flash[:success] = "内容を変更しました!"
   redirect_to user_path(@customer)
  else
   render :edit
  end
  end

  def quit
    @customer = current_customer
  end

  def out
    @customer = current_customer
    @customer.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def customer_params
   params.require(:customer).permit(:email, :name, :encrypted_password, :image, :is_deleted, :nickname, :gender)
  end
 end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/customers/favorites_helper.rb
module Customers::FavoritesHelper
end

app/views/customers/users/edit.html.erb
<div class="container">

	  <div class="row subtitle">
			<h2 class="head-line text-center title_h2 subtitle row">マイページ編集</h2>
		</div>

			 <%= form_with model: @customer, url:user_path(@customer), local:true do |f| %>

   <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
  Gender:
  <%= f.label :gender, :man %>
  <%= f.radio_button :gender, "男性" %>
  <%= f.label :gender, :woman %>
  <%= f.radio_button :gender, "女性" %>
  <%= f.label :gender, :other %>
  <%= f.radio_button :gender, "その他" %>
 </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <p></p>

  <div class="actions">
    <%= f.submit "編集保存", class: "btn btn-outline-info nav-link save col-2" %>
    <p></p>
    <%= link_to "退会する", user_quit_path(@customer), class: "btn btn-outline-danger nav-link col-2" %>
  </div>
  <% end %>

</div>

app/views/customers/users/index.html.erb
 <div class='container'>
 <div class="row subtitle">
    <h2><i class="fas fa-user-friends"></i>ユーザー一覧</h2>
  </div>

  <p></p>

  <div class="row">
    <table class="table striped">
      <thead>
        <tr>
          <th bgcolor="#EEEEEE">番号</th>
          <th bgcolor="#EEEEEE"></th>
          <th bgcolor="#EEEEEE">ニックネーム</th>
          <th bgcolor="#EEEEEE">性別</th>
          <th bgcolor="#EEEEEE">フォロー数</th>
          <th bgcolor="#EEEEEE">フォロワー数</th>
          <th bgcolor="#EEEEEE">フォローボタン</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer|%>
          <tr>
            <td class="text-left"><%=link_to customer.id, user_path(customer) %></td>
            <td class="text-left" ><%= customer.name %></td>
            <td class = "text-left"><%= customer.nickname %></td>
            <td class = "text-left"><%= customer.gender %></td>
            <td class = "text-left"><%= customer.followings.count %></td>
            <td class = "text-left"><%= customer.followers.count %></td>
            <td class = "text-left">
              <% unless current_customer == customer %>
                <% if current_customer.following?(customer) %>
                  <%= link_to "フォロー外す", user_relationships_path(customer.id), class: "btn btn-info", method: :delete %>
                <% else %>
                  <%= link_to "フォローする", user_relationships_path(customer.id), class: "btn btn-outline-info", method: :post %>
                <% end %>
              <% end %>
            </td>
          </tr>
          <% end %>
      </tbody>
    </table>
  </div>
  <%= paginate @customers %>
</div>
</div>

app/views/customers/users/quit.html.erb
<div class="container subtitle">
  <div class="row justify-content-center subtitle">
      <h1 class="d-flex justify-content-center subtitle">本当に退会しますか？</h1>
  </div>

  <div class="row subtitle">
      <div class="col-12" align = "center">
        <div>
          <p>退会すると、会員情報や</p>
          <p>これまでの購入履歴が閲覧できなくなります。</p>
          <p>退会する場合は、「退会する」をクリックしてください。</p>
        </div>
      </div>

      <div class="col-12 subtitle" align = "center">
          <%= link_to '退会しない', root_path, class: "btn btn-outline-primary save col-xs-6" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <%= link_to "退会する", user_out_path, class: "btn btn-outline-danger col-xs-6", method: :patch, data: {confirm: "本当に退会しますか？"} %>
      </div>
  </div>
</div>

app/views/customers/users/show.html.erb
<div class="container">
  <h2 class="head-line text-center title_h2 subtitle row"><i class="fas fa-home"></i>マイページ</h2>
	  <div class="row subtitle">

      <div class ="col-md-7">
      	<h4><i class="fas fa-user-edit"></i>登録情報</h4>

			<table class="table table-bordered table-condensed" >
					<tbody>

            <% if current_customer == @customer %>
						<tr>
							<td bgcolor="#EEEEEE",class="info"><strong>氏名</strong></td>
							<td class="text-left"><%= @customer.name %></td>
						</tr>
						<% end %>

						<tr>
							<td bgcolor="#EEEEEE",class="info"><strong>ニックネーム</strong></td>
							<td class="text-left"><%= @customer.nickname %></td>
						</tr>

						<tr>
							<td bgcolor="#EEEEEE",class="info"><strong>性別</strong></td>
							<td class="text-left"><%= @customer.gender %></td>
						</tr>

                        <% if current_customer == @customer %>
						<tr>
							<td bgcolor="#EEEEEE",class="info"><strong>Eメール</strong></td>
							<td class="text-left"><%= @customer.email %></td>
						</tr>
						<% end %>

						<tr>
							<td bgcolor="#EEEEEE",class="info"><strong>退会フラグ</strong></td>
							<td class="text-left">
								<% if @customer.is_deleted == true %>
				          <strong class="text-info">退会</strong>
					      <% else %>
					        <strong class="text-info">有効</strong>
					      <% end %>
							</td>
						</tr>

						<!--tr>
							<td bgcolor="#EEEEEE",class="info"><strong>ブックマーク数</strong></td>
							<td class="text-left"><%#= link_to @customer.favorites.count, favorites_path(customer_id: @customer.id) %></td>
						</tr-->

						<tr>
							<td bgcolor="#EEEEEE",class="info"><strong>フォロー数</strong></td>
							<td class="text-left"><%= link_to @customer.followings.count, user_followings_path(@customer) %></td>
						</tr>

						<tr>
							<td bgcolor="#EEEEEE",class="info"><strong>フォロワー数</strong></td>
							<td class="text-left"><%= link_to @customer.followers.count, user_followers_path(@customer) %></td>
						</tr>

					</tbody>
			</table><br/>
			 <% if @customer.id == current_customer.id %>
				<%=link_to '編集', edit_user_path, class: "btn btn-outline-info" %>
				<%=link_to "ユーザー一覧", users_path, class: "btn btn-outline-secondary" %>
			 <% end %>
			 <td>
			  <% unless current_customer == @customer %>
        <% if current_customer.following?(@customer) %>
          <%= link_to "フォロー外す", user_relationships_path(@customer.id), class: "btn btn-info", method: :delete %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(@customer.id), class: "btn btn-outline-info", method: :post %>
        <% end %>
        <% end %>
       </td>

        <p></p>

			</div><br/>

      <div class="col-md-5">
    	<h4><i class="fas fa-clone"></i>投稿一覧</h4>
		<table class="table striped">
      <thead>
        <tr>
          <th bgcolor="#EEEEEE">観光地名</th>
          <th bgcolor="#EEEEEE">ジャンル</th>
          <th bgcolor="#EEEEEE">更新日</th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post|%>
          <tr>
            <td class="text-left" ><%= link_to post.name, post_path(post) %></td>
            <td class = "text-left"><%= post.genre.name %>
            <td class = "text-left"><%= post.updated_at.strftime('%Y/%m/%d')%></td>
          </tr>
         <% end %>
      </tbody>
		</table>
		 <%= paginate @posts %>
    </div>
		</div>
  </div>
	</div>
</div>