config/routes.rb
Rails.application.routes.draw do

#admin
devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
namespace :admins do

  resources :users,only: [:show,:edit,:update]
      get 'top'=>'users#top'
  resources :genres,only: [:index,:create,:edit,:update]
  resources :locations,only: [:index,:create,:edit,:update]

  root to: 'users#top'

end


#customers
devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
scope module: :customers do

  resources :users,only: [:index, :show, :new, :edit, :update] do
    resource :relationships, only: [:create, :destroy, :index]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      get 'quit'=>'users#quit'
      get 'out'=>'users#out'
  end
  resources :favorites,only: [:index]
  resources :genres,only: [:index]
  resources :locations,only: [:index]
  resources :relationships,only: [:index]
  resources :posts do
    resource :favorites,only: [:create, :destroy]
    resource :likes,only: [:create, :destroy]
  end

  get '/search' => 'search#search'

   root to: 'likes#about'
     get	'top' => 'likes#top'

  post "posts/:id/destroy" => "posts#destroy"

  devise_scope :user do
    get '/customers/sign_out' => 'devise/sessions#destroy'
  end
end

end

app/models/admin.rb
class Admin< ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord


  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 enum gender: { 男性: 1, 女性: 2, その他: 3}

 # 退会機能
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

has_many :relationships,class_name: "Relationship",  foreign_key: "follower_id",dependent: :destroy
has_many :passive_relationships,class_name: "Relationship", foreign_key: "followed_id",dependent: :destroy
has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人
has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
has_many :followings, through: :relationships, source: :followed

def follow(customer_id)
    unless self == customer_id
     self.relationships.find_or_create_by(followed_id: customer_id.to_i, follower_id: self.id)
    end
end

def unfollow(customer_id)
    relationships.find_by(followed_id: customer_id).destroy
end

def following?(customer)
    followings.include?(customer)
end

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :customer
  belongs_to :post
  belongs_to :genre
  belongs_to :location

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :posts
  has_many :favorites

end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :customer
  belongs_to :post

end

app/models/location.rb
class Location < ApplicationRecord

  has_many :posts
  has_many :locations

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :customer
  has_many :favorites, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_customers, through: :likes, source: :customer
  belongs_to :genre
  belongs_to :location

  scope :ranking, -> { left_joins(:likes).group("posts.id").select("posts.*, COUNT(likes.id) AS like_count").order("like_count desc") }

   attachment :image

  def liked_by?(customer)
    likes.where(customer_id: customer.id).exists?
  end

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end


end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "Customer"
  belongs_to :followed, class_name: "Customer"

end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!

  def top
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
    @posts = @customer.posts.page(params[:page]).per(10)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
  if @customer.update(customer_params)
   flash[:success] = "内容を変更しました!"
   redirect_to admins_user_path(@customer)
  else
   render :edit
  end
  end

  private

  def customer_params
   params.require(:customer).permit(:email, :name, :encrypted_password, :image, :is_deleted, :nickname, :gender)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

 # 新規登録の保存機能
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,
  			 keys: [:name, :nickname, :email, :gender, :encrypted_password, :is_deleted])
    end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nickname, :gender, :is_deleted])
  end

end

app/controllers/customers/users_controller.rb
class Customers::UsersController < ApplicationController
  before_action :authenticate_customer!

  def index
    @customers = Customer.page(params[:page]).per(10)
    @customer = current_customer
  end

  def show
    @customer = Customer.find(params[:id])
    @posts = @customer.posts.page(params[:page]).per(4)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
  if @customer.update(customer_params)
   flash[:success] = "内容を変更しました!"
   redirect_to user_path(@customer)
  else
   render :edit
  end
  end

  def quit
    @customer = current_customer
  end

  def out
    @customer = current_customer
    @customer.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def customer_params
   params.require(:customer).permit(:email, :name, :encrypted_password, :image, :is_deleted, :nickname, :gender)
  end
 end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/locations_helper.rb
module Admins::LocationsHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers/genres_helper.rb
module Customers::GenresHelper
end

app/helpers/customers/homes_helper.rb
module Customers::HomesHelper
end

app/helpers/customers/likes_helper.rb
module Customers::LikesHelper
end

app/helpers/customers/posts_helper.rb
module Customers::PostsHelper
end

app/helpers/customers/search_helper.rb
module Customers::SearchHelper
end

app/helpers/customers/users_helper.rb
module Customers::UsersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admins/users/edit.html.erb
<div class="container">

	  <div class="row subtitle">
			<h2 class="head-line text-center title_h2 subtitle row"><i class="fas fa-user-friends"></i>会員情報編集</h2>
		</div>

			 <%= form_with model: @customer, url:admins_user_path(@customer), local:true do |f| %>

   <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname, autofocus: true %>
  </div>

  <div class="field">
    Gender:
    <%= f.label :gender, :man %>
    <%= f.radio_button :gender, "男性" %>
    <%= f.label :gender, :woman %>
    <%= f.radio_button :gender, "女性" %>
    <%= f.label :gender, :other %>
    <%= f.radio_button :gender, "その他" %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :"members_status", class: "col-sm-4 control-label" %><br/>
  　<%= f.radio_button :is_deleted, false %>
  　<%= f.label :is_deleted, "有効", {value: :false, style: "display: inline-block;"} %>
  　<%= f.radio_button :is_deleted, true %>
  　<%= f.label :is_deleted, "退会", {value: :true, style: "display: inline-block;"} %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <p></p>

  <div class="actions">
    <%= f.submit "編集保存", class: "btn btn-outline-info nav-link save col-2" %>
  </div>
  <% end %>

</div>

app/views/admins/users/show.html.erb
<div class="container">
  <h2 class="head-line text-center title_h2 subtitle row"><i class="fas fa-user-friends"></i>会員情報</h2>
	  <div class="row subtitle">

   <div class ="col-md-7">
     <h4 class="head-line text-center title_h4 subtitle row">登録情報</h4>
			<table class="table table-bordered table-condensed" >
					<tbody>

						<tr>
							<td bgcolor="#EEEEEE",class="info"><strong>氏名</strong></td>
							<td class="text-left"><%= @customer.name %></td>
						</tr>

						<tr>
							<td bgcolor="#EEEEEE",class="info"><strong>ニックネーム</strong></td>
							<td class="text-left"><%= @customer.nickname %></td>
						</tr>

						<tr>
							<td bgcolor="#EEEEEE",class="info"><strong>性別</strong></td>
							<td class="text-left"><%= @customer.gender %></td>
						</tr>

						<tr>
							<td bgcolor="#EEEEEE",class="info"><strong>Eメール</strong></td>
							<td class="text-left"><%= @customer.email %></td>
						</tr>

						<tr>
							<td bgcolor="#EEEEEE",class="info"><strong>退会フラグ</strong></td>
							<td class="text-left">
								<% if @customer.is_deleted == true %>
                  <strong class="text-info">退会</strong>
	              <% else %>
	                <strong class="text-info">有効</strong>
	              <% end %>
							</td>
						</tr>

						<tr>
							<td bgcolor="#EEEEEE",class="info"><strong>お気に入り数</strong></td>
							<td class="text-left"><%= @customer.favorites.count %></td>
						</tr>

						<tr>
							<td bgcolor="#EEEEEE",class="info"><strong>フォロー数</strong></td>
							<td class="text-left"><%= @customer.followings.count %></td>
						</tr>

						<tr>
							<td bgcolor="#EEEEEE",class="info"><strong>フォロワー数</strong></td>
							<td class="text-left"><%= @customer.followers.count %></td>
						</tr>

					</tbody>
			</table><br/>
				<%=link_to '編集', edit_admins_user_path, class: "btn btn-outline-info" %>
				<%=link_to "ユーザー一覧", admins_top_path, class: "btn btn-outline-secondary" %>

        <p></p>

			</div><br/>

      <div class="col-md-5">
    	<h4 class="head-line text-center title_h4 subtitle row">投稿一覧</h4>
		<table class="table striped">
      <thead>
        <tr>
          <th bgcolor="#EEEEEE">番号</th>
          <th bgcolor="#EEEEEE">観光地名</th>
          <!--<th bgcolor="#EEEEEE">ジャンル</th>-->
          <th bgcolor="#EEEEEE">更新日</th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post|%>
          <tr>
            <td class="text-left"><%= post.id %></td>
            <td class="text-left" ><%= post.name %></td>
            <!--<td class = "text-left">--><%#= posts.genre.name %>
            <td class = "text-left"><%= post.updated_at.strftime('%Y/%m/%d')%></td>
          </tr>
         <% end %>
      </tbody>
		</table>
    </div>
  </div>
</div>

app/views/admins/users/top.html.erb
<div class='container'>
 <div class="row subtitle">
    <h2 style="display: inline;"><i class="fas fa-user-friends"></i>ユーザー一覧</h2>
  </div>

  <p></p>

  <div class="row">
    <table class="table striped">
      <thead>
        <tr>
          <th bgcolor="#EEEEEE">番号</th>
          <th bgcolor="#EEEEEE"></th>
          <th bgcolor="#EEEEEE">ニックネーム</th>
          <th bgcolor="#EEEEEE">性別</th>
          <th bgcolor="EEEEEE">Eメール</th>
          <th bgcolor="EEEEEE">退会ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer|%>
          <tr>
            <td class="text-left"><%=link_to customer.id, admins_user_path(customer) %></td>
            <td class="text-left" ><%= customer.name %></td>
            <td class = "text-left"><%= customer.nickname %></td>
            <td class = "text-left"><%= customer.gender %></td>
            <td class = "text-left"><%= customer.email %></td>
            <td class = "text-left">
                <% if customer.is_deleted == true %>
                  <strong class="text-info">退会</strong>
	              <% else %>
	                <strong class="text-info">有効</strong>
	              <% end %>
							</td>
            </td>
          </tr>
          <% end %>
      </tbody>
    </table>
  </div>

<%= paginate @customers %>

</div>
</div>