config/routes.rb
Rails.application.routes.draw do

#admin
devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
namespace :admins do

  resources :users,only: [:show,:edit,:update]
      get 'top'=>'users#top'
  resources :genres,only: [:index,:create,:edit,:update]
  resources :locations,only: [:index,:create,:edit,:update]

  root to: 'users#top'

end


#customers
devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
scope module: :customers do

  resources :users,only: [:index, :show, :new, :edit, :update] do
    resource :relationships, only: [:create, :destroy, :index]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      get 'quit'=>'users#quit'
      get 'out'=>'users#out'
  end
  resources :favorites,only: [:index]
  resources :genres,only: [:index]
  resources :locations,only: [:index]
  resources :relationships,only: [:index]
  resources :posts do
    resource :favorites,only: [:create, :destroy]
    resource :likes,only: [:create, :destroy]
  end

  get '/search' => 'search#search'

   root to: 'likes#about'
     get	'top' => 'likes#top'

  post "posts/:id/destroy" => "posts#destroy"

  devise_scope :user do
    get '/customers/sign_out' => 'devise/sessions#destroy'
  end
end

end

app/models/customer.rb
class Customer < ApplicationRecord


  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 enum gender: { 男性: 1, 女性: 2, その他: 3}

 # 退会機能
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

has_many :relationships,class_name: "Relationship",  foreign_key: "follower_id",dependent: :destroy
has_many :passive_relationships,class_name: "Relationship", foreign_key: "followed_id",dependent: :destroy
has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人
has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
has_many :followings, through: :relationships, source: :followed

def follow(customer_id)
    unless self == customer_id
     self.relationships.find_or_create_by(followed_id: customer_id.to_i, follower_id: self.id)
    end
end

def unfollow(customer_id)
    relationships.find_by(followed_id: customer_id).destroy
end

def following?(customer)
    followings.include?(customer)
end

end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :customer
  belongs_to :post

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/favorites_controller.rb
class Customers::FavoritesController < ApplicationController
 before_action :authenticate_customer!

  def create
    post = Post.find(params[:post_id])
    favorite = current_customer.favorites.new(post_id: post.id)
    favorite.save
    redirect_to posts_path
  end

  def destroy
    post = Post.find(params[:post_id])
    favorite = current_customer.favorites.find_by(post_id: post.id)
    favorite.destroy
    redirect_to posts_path
  end

  def index
    @posts = Post.page(params[:page]).per(10)
    @customer = Customer.find(params[:customer_id])
  end

end

app/controllers/customers/genres_controller.rb
class Customers::GenresController < ApplicationController
  before_action :authenticate_customer!

  def index
    @posts = Post.page(params[:page]).per(10)
  end
end

app/controllers/customers/homes_controller.rb
class Customers::HomesController < ApplicationController
end

app/controllers/customers/likes_controller.rb
class Customers::LikesController < ApplicationController
  before_action :authenticate_customer!

  def top
     @posts = Post.ranking.take(5)  #takeで上位５個を表示という意味、またはtakeじゃなくてlimitでも可能
     @genres = Genre.all
     @post = Post.order(created_at: :desc).limit(10)
  end

  def about
  end

  def create
    post = Post.find(params[:post_id])
    like = current_customer.likes.new(post_id: post.id)
    like.save
    redirect_to post_path(post)
  end

  def destroy
    post = Post.find(params[:post_id])
    like = current_customer.likes.find_by(post_id: post.id)
    like.destroy
    redirect_to post_path(post)
  end

end

app/controllers/customers/locations_controller.rb
class Customers::LocationsController < ApplicationController
   before_action :authenticate_customer!

   def index
   end

end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/posts_controller.rb
class Customers::PostsController < ApplicationController
 before_action :authenticate_customer!

 def index
  @posts = Post.page(params[:page]).per(6)
 end

 def new
  @post = Post.new
  @customer = Customer.new
 end

 def create
  @post = Post.new(post_params)
  @post.customer_id = current_customer.id
  if @post.save
   flash[:success] = "投稿しました!"
   redirect_to post_path(@post.id)
  else
   render :new
  end
 end

 def show
  @post = Post.find(params[:id])
  @customer = @post.customer
 end

 def edit
  @post = Post.find(params[:id])
 end

 def update
   @post = Post.find(params[:id])
  if @post.update(post_params)
   flash[:success] = "投稿内容を変更しました!"
   redirect_to post_path(@post)
  else
   render :edit
  end
 end

 def destroy
  @post = Post.find_by(id: params[:id])
  @post.destroy
  redirect_to posts_path
 end

 private

  def post_params
   params.require(:post).permit(:image, :name, :customer_id, :genre_id, :location_id, :statement, :evaluation, :address)
  end

 end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/relationships_controller.rb
class Customers::RelationshipsController < ApplicationController
  before_action :authenticate_customer!

  def create
    current_customer.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_customer.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    customer = Customer.find(params[:user_id])
    @customers = customer.followings
  end

  def followers
    customer = Customer.find(params[:user_id])
    @customers = customer.followers
  end

end

app/controllers/customers/search_controller.rb
class Customers::SearchController < ApplicationController
  before_action :authenticate_customer!

  def search
    @value = params["search"]["value"]         #データを代入
    @how = params["search"]["how"]             #データを代入
    @datas = search_for(@how, @value)          #def search_forを実行(引数に検索ワードと検索方法)
  end

  private

  def location(value)
    #.orを使用することで、valueに一致するカラムのデータをnameカラムとgenre_idカラムから探してきます。
    target_location_id = Location.find_by(name: value)&.id
    Post.where(location_id: target_location_id)
  end

  def customer(value)
    target_customer_id = Customer.find_by(nickname: value)&.id
    Post.where(customer_id: target_customer_id)
  end

  def genre(value)
    target_genre_id = Genre.find_by(name: value)&.id
    Post.where(genre_id: target_genre_id)
  end

  def post(value)
    Post.where("name LIKE ?", "#{value}%")
  end


  def search_for(how, value)
    case how                     #引数のhowと一致する処理に進むように定義しています。
    when 'location'                 #ジャンル検索の場合はmatchで固定してるので、必ず'match'の処理に進みます。
      location(value)
    when 'customer'
      customer(value)
    when 'genre'
      genre(value)
    when 'post'
      post(value)
    end
  end

end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def reject_inactive_customer
  @cusomer = Customer.find_by(name: params[:customer][:name])
    if @user
      if @customer.valid_password?(params[:cusomer][:password]) && !@cusomer.is_deleted
        redirect_to new_registration_path(resource_name)
      end
    end
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/users_controller.rb
class Customers::UsersController < ApplicationController
  before_action :authenticate_customer!

  def index
    @customers = Customer.page(params[:page]).per(10)
    @customer = current_customer
  end

  def show
    @customer = Customer.find(params[:id])
    @posts = @customer.posts.page(params[:page]).per(4)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
  if @customer.update(customer_params)
   flash[:success] = "内容を変更しました!"
   redirect_to user_path(@customer)
  else
   render :edit
  end
  end

  def quit
    @customer = current_customer
  end

  def out
    @customer = current_customer
    @customer.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def customer_params
   params.require(:customer).permit(:email, :name, :encrypted_password, :image, :is_deleted, :nickname, :gender)
  end
 end

app/helpers/customers/favorites_helper.rb
module Customers::FavoritesHelper
end

app/helpers/customers/genres_helper.rb
module Customers::GenresHelper
end

app/helpers/customers/homes_helper.rb
module Customers::HomesHelper
end

app/views/customers/likes/about.html.erb
  <div class='container'>
    <div class="about">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1 id="aaa" class="title">
          <span>A</span>
          <span>b</span>
          <span>o</span>
          <span>u</span>
          <span>t</span>
      </h1>

      <p>このサイトは東京に特化した</p>
      <p>投稿型観光サイトです</p>
      <p>コロナ禍ではありますが</p>
      <p>みなさんにとって素晴らしい思い出が</p>
      <p>作れますように</p>
       </div>
    </div>
  </div>

app/views/customers/likes/top.html.erb
<div class='container'>

  <div class="row subtitle">
    <div class="col-2">
      <% if customer_signed_in? %>                        <!--deviseのヘルパーメソッドです、省いても問題ありません。-->
        <h5><i class="fas fa-search-plus"></i>投稿検索</h5>
        <%= form_with url: search_path, method: :get, local: true do |f| %>
          <%= f.text_field 'search[value]', size: "18x3" %><br>
          <span class="search-button col-xs-12 text-right">
            <%= f.select 'search[how]', options_for_select({ "観光地" => "post", "投稿者" => "customer", "ジャンル" => "genre", "エリア" => "location" }) %>
            <%= f.submit :"検索" %>
          </span>
        <% end %>
      <% end %>
      <p></p>
      <table class="table table-bordered genre-table">
        <thead>
          <tr class="border">
            <th>ジャンル検索</th>
          </tr>
        </thead>
        <tbody>
          <% @genres.first(5).each do |genre| %>
          <tr>
            <td>
              <%= link_to genre.name, search_path('search[value]': genre.name, 'search[how]': "genre") %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%=link_to 'Googleマップ検索ページへ', locations_path, class: "btn btn-outline-info" %>
    </div>

    <div class='col-1'></div>

    <div class="col-md-5">
    <h2 style="display: inline;"><i class="fas fa-medal"></i>人気投稿ランキング</h2>
    <p></p>

    <div class="row">
      <% tmp_like_count = 0 %> <!-- お気に入りを数えるときは０からという意味-->
      <% rank = 1 %> <!--ランキング１位からっていう意味-->
        <% @posts.each.with_index(1) do |post, i| %>
        <div class="rank-item">
            <!--同率順位表示-->
            <% if post.likes.count == tmp_like_count %> <!--もしお気に入りの数と数えたお気に入りの数が同じなら-->
              <h4><i class="fas fa-crown"></i>第<%= rank %>位</h4> <!--ランキングはそのまま＝同率 -->
            <% else %>
              <% rank = i %> <!--もし同じじゃないならeachのループ分だけの順位になる-->
              <h4><i class="fas fa-crown"></i>第<%= rank %>位</h4> <!--普通に順位更新-->
            <% end %>
            <% tmp_like_count = post.likes.count %> <!--ランキングの度にその時のお気に入りの数を比べ、同じならif違ったらelse-->
          <div class="rank-image"><%= attachment_image_tag post, :image ,size: "400x200", fallback: "no_image.jpg", class: "rounded" %></div>
          <section class="rank-text">
          <h4 class="post-text-heading">『<%=  link_to post.name, post_path(post)  %>』</h4>
            <span class="category">ジャンル:<%= post.genre.name %><br/>
              <% if post.location.present? %>
                エリア:<%= post.location.name %>
              <% end %>
            </span>
            <p class="post-name">投稿者:<%= link_to post.customer.nickname, user_path(post.customer) %> / <%= post.customer.gender %></p>
          </section>
      </div>
      <% end %>
    </div>
    </div>

    <div class="col-md-4">
    <h2><i class="fas fa-external-link-alt"></i>最新投稿</h2>
    <p></p>

    <div class="row">
    <table class="table striped">
      <thead>
        <tr>
          <th bgcolor="#EEEEEE">観光地名</th>
          <th bgcolor="#EEEEEE">投稿者</th>
          <th bgcolor="#EEEEEE">更新日</th>
        </tr>
      </thead>
      <% @post.each do |post|%>
      <tbody>
            <td class="text-left" ><%= link_to post.name, post_path(post) %></td>
            <td class="text-left" ><%= link_to post.customer.nickname, user_path(post.customer) %></td>
            <td class = "text-left"><%= post.updated_at.strftime('%Y/%m/%d')%></td>
      </tbody>
      <% end %>
      </table>
     </div>
  </div>
</div>
</div>
</div>